Hw3 Никита Митцев Б10
danyaberezun/Linux-basics-2020 pull request #34
Opened 2020-09-29 18:48 UTC by muldrik

2020-10-07 22:33 UTC, sloboegen98 commented on seminar03/task02/task02.sh
> +factor $NUM | grep -qE '^(.*): \1$' && echo "$NUM true" || echo "$NUM false"
:+1:

2020-10-07 22:34 UTC, sloboegen98 commented on seminar03/task04/task04.sh
> +SUM=0; for i in `cat numbers.txt`; do SUM=$(($SUM + $i)); done; echo $SUM
а это точно факториалы?

2020-10-07 22:36 UTC, sloboegen98 commented on seminar03/task06/task06.sh
> +cat <file.txt | while read -r s  || [ -n "$s" ]
My bad, что не добавил в файле перевод строки в конце...

2020-10-07 22:38 UTC, sloboegen98 requested changes
1 2 3 6 зачтены. Остальные можно досдавать

2020-10-12 13:16 UTC, muldrik commented
Задания 4, 5, 7 в прошлый раз просто удалились, видимо куда-то не туда запушил. Добавил снова.

2020-10-15 11:29 UTC, sloboegen98 commented on seminar03/task04/task04.sh
> +for i in `cat numbers.txt`; do echo $(seq -s "*" 1 $i | bc);  done;
круто!

2020-10-15 11:31 UTC, sloboegen98 approved these changes

2020-10-15 11:31 UTC, closed without merging